[tool.pyflow]
name = "laskea"
py_version = "3.8"
# [[[fill version_sync()]]]
version = "2022.7.30"
# [[[end]]] (checksum: 023dfa4bb4e571cbcf7aa76364ab553f)
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
